// @title           LockIn API
// @version         1.0
// @description     Adaptive learning backend — quiz generation, sessions, and progress tracking.
// @termsOfService  http://swagger.io/terms/
//
// @contact.name   LockIn Support
// @contact.url    https://github.com/acerowl/lockin
//
// @license.name  MIT
//
// @host      localhost:8080
// @BasePath  /api/v1
//
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and the JWT token.
package main

import (
	"log"
	"os"

	_ "github.com/acerowl/lockin/backend/docs" // generated by swag init
	"github.com/acerowl/lockin/backend/internal/ai"
	"github.com/acerowl/lockin/backend/internal/db"
	"github.com/acerowl/lockin/backend/internal/handlers"
	"github.com/acerowl/lockin/backend/internal/middleware"
	"github.com/acerowl/lockin/backend/internal/repository"
	"github.com/acerowl/lockin/backend/internal/service"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/joho/godotenv"
	fiberSwagger "github.com/swaggo/fiber-swagger"
)

func main() {
	if err := godotenv.Load(); err != nil {
		log.Println("No .env file found or error loading it")
	}

	if err := db.Connect(); err != nil {
		log.Fatalf("Database connection failed: %v", err)
	}
	defer db.Close()

	app := fiber.New()
	app.Use(logger.New())
	// app.Use(logger.New(logger.Config{
    //     Format: "[${time}] ${status} - ${latency} ${method} ${path}\nReqBody: ${body}\nResBody: ${resBody}\n",
    // }))
	// CORS middleware for mobile client
	app.Use(cors.New(cors.Config{
		AllowOrigins: "*",
		AllowHeaders: "Origin, Content-Type, Accept, Authorization",
	}))

	app.Get("/health", func(c *fiber.Ctx) error {
		return c.JSON(fiber.Map{"status": "ok"})
	})

	// Swagger UI — available at /docs/index.html
	app.Get("/docs/*", fiberSwagger.WrapHandler)

	aiProviderType := os.Getenv("AI_PROVIDER")
	provider := ai.NewAIProvider(aiProviderType)

	aiGen := ai.NewGenerator(db.Pool, provider)

	// Initialize Repositories
	userRepo := repository.NewUserRepository(db.Pool)
	topicRepo := repository.NewTopicRepository(db.Pool)
	moduleRepo := repository.NewModuleRepository(db.Pool)
	lessonRepo := repository.NewLessonRepository(db.Pool)
	sessionRepo := repository.NewSessionRepository(db.Pool)

	// Initialize Services
	authService := service.NewAuthService(userRepo)
	topicService := service.NewTopicService(topicRepo, aiGen)
	moduleService := service.NewModuleService(moduleRepo)
	lessonService := service.NewLessonService(lessonRepo, moduleRepo)
	sessionService := service.NewSessionService(sessionRepo, topicRepo, userRepo, aiGen)

	// Initialize API Handler
	apiHandler := handlers.NewAPIHandler(authService, topicService, moduleService, lessonService, sessionService)

	api := app.Group("/api/v1")
	authGroup := api.Group("/auth")
	authGroup.Post("/register", apiHandler.Register)
	authGroup.Post("/login", apiHandler.Login)
	authGroup.Post("/refresh", apiHandler.RefreshToken)

	usersGroup := api.Group("/users", middleware.Protected())
	usersGroup.Get("/me", apiHandler.GetMe)

	topicsGroup := api.Group("/topics", middleware.Protected())
	topicsGroup.Get("/", apiHandler.ListTopics)
	topicsGroup.Post("/", apiHandler.CreateTopic)
	topicsGroup.Get("/:id", apiHandler.GetTopic)
	topicsGroup.Get("/roadmap/:id", apiHandler.GetRoadmap)

	moduleGroup := api.Group("/modules", middleware.Protected())
	moduleGroup.Post("/status/:id", apiHandler.UpdateModuleStatus)

	lessonGroup := api.Group("/lessons",middleware.Protected())
	lessonGroup.Post("/progress/:id", apiHandler.Progress)


	sessionsGroup := api.Group("/sessions", middleware.Protected())
	sessionsGroup.Post("/start", apiHandler.StartSession)
	sessionsGroup.Post("/:id/complete", apiHandler.CompleteSession)
	sessionsGroup.Get("/activity", apiHandler.GetUserActivity)



	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	log.Printf("Server starting on port %s", port)
	if err := app.Listen(":" + port); err != nil {
		log.Fatalf("Server failed to start: %v", err)
	}
}
