// @title           LockIn API
// @version         1.0
// @description     Adaptive learning backend — quiz generation, sessions, and progress tracking.
// @termsOfService  http://swagger.io/terms/
//
// @contact.name   LockIn Support
// @contact.url    https://github.com/acerowl/lockin
//
// @license.name  MIT
//
// @host      localhost:8080
// @BasePath  /api/v1
//
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and the JWT token.
package main

import (
	"log"
	"os"
	"os/signal"
	"syscall"

	_ "github.com/acerowl/lockin/backend/docs" // generated by swag init
	"github.com/acerowl/lockin/backend/internal/ai"
	"github.com/acerowl/lockin/backend/internal/config"
	"github.com/acerowl/lockin/backend/internal/db"
	"github.com/acerowl/lockin/backend/internal/handlers"
	"github.com/acerowl/lockin/backend/internal/middleware"
	"github.com/acerowl/lockin/backend/internal/repository"
	"github.com/acerowl/lockin/backend/internal/service"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/compress"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/helmet"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/fiber/v2/middleware/recover"
	fiberSwagger "github.com/swaggo/fiber-swagger"
)

func main() {
	// Load configuration
	cfg := config.Load()

	// Connect to database
	if err := db.Connect(); err != nil {
		log.Fatalf("Database connection failed: %v", err)
	}
	defer db.Close()

	// Initialize Fiber app with timeouts
	app := fiber.New(fiber.Config{
		ReadTimeout:  cfg.ReadTimeout,
		WriteTimeout: cfg.WriteTimeout,
		IdleTimeout:  cfg.IdleTimeout,
		AppName:      "LockIn API v1.0",
		// Centralized Error Handler
		ErrorHandler: func(c *fiber.Ctx, err error) error {
			code := fiber.StatusInternalServerError
			if e, ok := err.(*fiber.Error); ok {
				code = e.Code
			}
			return c.Status(code).JSON(fiber.Map{
				"success": false,
				"error":   err.Error(),
			})
		},
	})

	// Production Middleware Stack
	app.Use(recover.New())  // Recover from panics
	app.Use(helmet.New())   // Security headers
	app.Use(compress.New()) // Gzip/Brotli compression
	app.Use(logger.New(logger.Config{
		Format: "[${time}] ${status} - ${latency} ${method} ${path}\n",
	}))

	// CORS middleware for mobile/web clients
	app.Use(cors.New(cors.Config{
		AllowOrigins: "*",
		AllowHeaders: "Origin, Content-Type, Accept, Authorization",
	}))

	// Health check
	app.Get("/health", func(c *fiber.Ctx) error {
		return c.JSON(fiber.Map{"status": "ok"})
	})

	// Swagger UI
	app.Get("/docs/*", fiberSwagger.WrapHandler)

	// Dependency Injection
	provider := ai.NewAIProvider(cfg.AIProvider)
	aiGen := ai.NewGenerator(db.Pool, provider)

	userRepo := repository.NewUserRepository(db.Pool)
	topicRepo := repository.NewTopicRepository(db.Pool)
	moduleRepo := repository.NewModuleRepository(db.Pool)
	lessonRepo := repository.NewLessonRepository(db.Pool)
	sessionRepo := repository.NewSessionRepository(db.Pool)

	authService := service.NewAuthService(userRepo)
	topicService := service.NewTopicService(topicRepo, aiGen)
	moduleService := service.NewModuleService(moduleRepo)
	lessonService := service.NewLessonService(lessonRepo, moduleRepo)
	sessionService := service.NewSessionService(sessionRepo, topicRepo, userRepo, aiGen)

	apiHandler := handlers.NewAPIHandler(aiGen, authService, topicService, moduleService, lessonService, sessionService)

	// API Routes
	api := app.Group("/api/v1")
	authGroup := api.Group("/auth")
	authGroup.Post("/register", apiHandler.Register)
	authGroup.Post("/login", apiHandler.Login)
	authGroup.Post("/refresh", apiHandler.RefreshToken)
	authGroup.Post("/forgot-password", apiHandler.ForgotPassword)

	usersGroup := api.Group("/users", middleware.Protected())
	usersGroup.Get("/me", apiHandler.GetMe)

	topicsGroup := api.Group("/topics", middleware.Protected())
	topicsGroup.Get("/", apiHandler.ListTopics)
	topicsGroup.Post("/", apiHandler.CreateTopic)
	topicsGroup.Get("/:id", apiHandler.GetTopic)
	topicsGroup.Get("/roadmap/:id", apiHandler.GetRoadmap)
	topicsGroup.Post("/assessment", apiHandler.CreateTopicAssessment)
	topicsGroup.Post("/assessment/evaluate", apiHandler.EvaluateTopicAssessment)

	moduleGroup := api.Group("/modules", middleware.Protected())
	moduleGroup.Post("/status/:id", apiHandler.UpdateModuleStatus)

	lessonGroup := api.Group("/lessons", middleware.Protected())
	lessonGroup.Post("/progress/:id", apiHandler.Progress)

	sessionsGroup := api.Group("/sessions", middleware.Protected())
	sessionsGroup.Post("/start", apiHandler.StartSession)
	sessionsGroup.Post("/:id/complete", apiHandler.CompleteSession)
	sessionsGroup.Get("/activity", apiHandler.GetUserActivity)

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, os.Interrupt, syscall.SIGTERM)

	go func() {
		<-quit
		log.Println("Shutting down server...")
		if err := app.ShutdownWithTimeout(cfg.ShutdownTimeout); err != nil {
			log.Printf("Server shutdown error: %v", err)
		}
	}()

	// Start Server
	log.Printf("Server starting on port %s", cfg.Port)
	if err := app.Listen(":" + cfg.Port); err != nil {
		log.Printf("Server stopped: %v", err)
	}

	log.Println("Cleanup tasks completed. Goodbye!")
}
